### Register user
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "secret1234"
}

### Login user
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "secret1234"
}

### Login demo user (Je le créais en dur dans AuthService)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "demo@petcare.local",
  "password": "demo1234"
}
