server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/petcare
    username: petcare
    password: petcare
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info

petcare:
  security:
    jwt-secret: "change-this-super-secret-key-for-prod-32chars-min"
    jwt-expiration-ms: 3600000 # 1 heure

